### ISSUE TITLE
Data Structure Name :: Graph

### ISSUE THREAD

**Issue by TheFenrisLycaon** [TheFenrisLycaon/DSA-C--#1]
Structure Name :: Graph
Structure Language :: C++

**Comment by tom635** [comment]
@TheFenrisLycaon  Assign me this issue

**Comment by TheFenrisLycaon** [comment]
@tom635 go ahead make the changes.

**Comment by tom635** [comment]
@TheFenrisLycaon  sir assign me I 
Shouid I add a new folder
sorry For delay

**Comment by TheFenrisLycaon** [comment]
Just put all your code inside a file and put it under structures. If that file creosses 500 lines, put the algorithms seperately in Algorithms folder. 

I'd you do end up doing the later, plase make seperate issues and pull requests. Also, make sure that you don't upload codes that are already there. 

See bst.cpp ofr example.
