### ISSUE TITLE
Algorithm Name :: Lowest Common Ancestor

### ISSUE THREAD

**Issue by vineetsharma36** [TheFenrisLycaon/DSA-C--#17]
Algo Name :: Lowest Common Ancestor
Algo Complexity :: O(n)
Algo Language :: C++

**Comment by ganesh1729ganesh** [comment]
I want to contribute to this . Please assign this to me.

**Comment by TheFenrisLycaon** [comment]
@ganesh1729ganesh Read the DOCS properly.
