### ISSUE TITLE
Algorithm Name :: Breadth First Search

### ISSUE THREAD

**Issue by iMohitPant** [TheFenrisLycaon/DSA-C--#21]
Algo Name :: Breadth First Search
Algo Complexity :: O(vertices + edges)
Algo Language :: C++

**Comment by iMohitPant** [comment]
I am working on this issue.

**Comment by ganesh1729ganesh** [comment]
I want to contribute to this . Please assign this to me.

**Comment by iMohitPant** [comment]
@ganesh1729ganesh  open your own issues. I am already working on it.

**Comment by ganesh1729ganesh** [comment]
ok fine.
