### ISSUE TITLE
Algorithm Name :: Binary Search 

### ISSUE THREAD

**Issue by shivanithorve01** [TheFenrisLycaon/DSA-C--#62]
- Algo Name :: Binary Search

- Algo Complexity :: O(log n)

- Algo Language :: C++ / Java

Hello @TheFenrisLycaon , I am Shivani and I want to contribute to your repo for Hacktoberfest2021. Can you please assign this issue to me ?

**Comment by TheFenrisLycaon** [comment]
Make a new Java folder like python. It should contain two directories. Structure and Algorithm. Add your code inside the algo one.

**Comment by TheFenrisLycaon** [comment]
If you can you may also contribute structure codes. They need to be a seperate issue though.

**Comment by shivanithorve01** [comment]
I will be happy contribute to this repo with more codes
