### ISSUE TITLE
Algorithm Name :: Count Sort

### ISSUE THREAD

**Issue by markswitch** [TheFenrisLycaon/DSA-C--#63]
Algo Name :: Count Sort
Algo Complexity :: O(n)
Algo Language :: C++

Hi @TheFenrisLycaon  ! I am new to open source and would love to contribute to this repository for Hacktoberfest'21. Can you please assign this issue.

**Comment by TheFenrisLycaon** [comment]
Go ahead. Make the PR.

**Comment by markswitch** [comment]
Hey, I made the Pull Request for the algorithm and sorry for the delay, was reading about branches in git.

**Comment by TheFenrisLycaon** [comment]
Merged.
