### ISSUE TITLE
Algorithm Name :: Linear Search

### ISSUE THREAD

**Issue by janhavikale06** [TheFenrisLycaon/DSA-C--#65]
Algo Name :: Linear Search
Algo Complexity :: O(n)
Algo Language :: Java
Hello @TheFenrisLycaon . I'm new to open source , I would love to contribute to this repository for Hacktoberfest2021. Can you please assign this issue.

**Comment by TheFenrisLycaon** [comment]
Welcome to open source. Please be sure to read the Contributing Guidelines for getting started. Refer back to  this comment section in case you find any difficulties or need more info.
